- hosts: terraform-ansible
  tasks:
    - name: Instalando python3
      apt:
        pkg:
        - python3
        update_cache: yes
      become: yes
    - name: Criar diretório /home/mine
      file:
        path: /home/ubuntu/mine
        state: directory
        mode: '0777'
      become: yes
      file:
        path: /home/ubuntu/mine/serv
        state: directory
        mode: '0777'
      become: yes
    - name: Baixar Aquivo JDK
      get_url:
        url: https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz
        dest: /home/ubuntu/mine/jdk-21_linux-aarch64_bin.tar.gz
        mode: '0644'
        owner: ubuntu
        group: ubuntu
    - name: Extrair arquivo JDK
      ansible.builtin.unarchive:
        src:  /home/ubuntu/mine/jdk-21_linux-aarch64_bin.tar.gz
        dest: /opt
        remote_src: yes
      become: yes
    - name: Baixar Mine-Serv
      get_url:
        url: https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar
        dest: /home/ubuntu/mine/serv/minecraft_server.jar
    - name: Executar Mine-Serv
      ansible.builtin.shell:
        cmd: |
          echo 'eula=true' > /home/ubuntu/mine/serv/eula.txt
          cd /home/ubuntu/mine/serv
          nohup /opt/jdk-21.0.2/bin/java -Xmx512M -Xms512M -jar /home/ubuntu/mine/serv/minecraft_server.jar nogui > /home/ubuntu/mine/serv/server.log 2>&1 &